

export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const GET_SELECTED_USER = "GET_SELECTED_USER";
export const DELETE_SELECTED_USER = "DELETE_SELECTED_USER";
export const SET_TAGS_TO_USER = "SET_TAGS_TO_USER";

